### PR TITLE
Syntax highlighter

### PR DESCRIPTION
**Pull request by ghost**
Added syntax highlighter in config editor (nginx mode)
Added added check for existence of a directory nginx config

### CODE REVIEW

**Comment by schenkd** [comment]
Hey @foozzi, thanks for your PR. I was glad to see that you were able to implement the editor so quickly. The ACE-Editor looks really good too. I noticed three points that still need to be adjusted before I can confirm the PR.

**Point 1:**
I guess the color palette is a matter of taste. I would prefer something simpler that fits the color scheme of nginx-ui, like chrome theme. I think a feature in the future release will probably be a dark theme. hehe. Then Monokai fits great. But until then I would like to have something that matches the white background.

**Point 2:**
I checked the github project of ACE Editor and found the following in the LICENSE agreement:
_Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Ajax.org B.V. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission._
This has to be done before we can use the ACE editor in nginx ui.

**Point 3:**
The configuration pages of the domains have not yet implemented the code editor. This leads to a break in the design of the application. I would be happy if you use it there as well.

If the points are fulfilled I am ready to accept the PR. Would you still do it?

Best David

**Review by schenkd — CHANGES_REQUESTED** [review]
Hey @foozzi, thanks for your PR. I was glad to see that you were able to implement the editor so quickly. The ACE-Editor looks really good too. I noticed three points that still need to be adjusted before I can confirm the PR.

**Point 1:**
I guess the color palette is a matter of taste. I would prefer something simpler that fits the color scheme of nginx-ui, like chrome theme. I think a feature in the future release will probably be a dark theme. hehe. Then Monokai fits great. But until then I would like to have something that matches the white background.

**Point 2:**
I checked the github project of ACE Editor and found the following in the LICENSE agreement:
_Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* Neither the name of Ajax.org B.V. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission._

This has to be done before we can use the ACE editor in nginx ui.

**Point 3:**
The configuration pages of the domains have not yet implemented the code editor. This leads to a break in the design of the application. I would be happy if you use it there as well.

If the points are fulfilled I am ready to accept the PR. Would you still do it?

Best David

**Comment by foozzi** [comment]
Hi @schenkd ! 
Thank you for response.

I was on vacation for some time, I think from tomorrow I will fulfill all points

Best regards Igor!

**Comment by foozzi** [comment]
**Point 2 resolved:** https://github.com/ajaxorg/ace/issues/4337

**Comment by foozzi** [comment]
@schenkd Hi! Look at the changes and https://github.com/ajaxorg/ace/issues/4337

**Comment by causefx** [comment]
safe to say Project dead?

**Review by schenkd — APPROVED** [review]
accepted

**Pull request merged**
